print('Now let\'s start part 3 of day 2.')
print('Already we have learned text, calculation and input function. Now we are gonna learn something new.')
print('So, now our new topic is int, float and str.')
print('Let\'s calculate of a person\'s Mother\'s age.')
name = input('What is your name? ')
Birth_year = int(input('What is your mother\'s year of birth? '))
Current_year = 2026
print(f'Congratulations dear. your mom is {Current_year - Birth_year} years old now.')
exam = input('Now enter your last academic examination ')
GPA = float(input(f'Enter your GPA of your {exam} examination. '))
math = float(input(f'What was your GPA of Mathematics in your {exam} examination? '))
print(f'The GPA difference is only {GPA - math} point, which is so good')
print(f'Congratulations {name}!! We are pleased to inform you that your GPA point {GPA} specially in mathematics GPA {math} is very good. Now you are eligible to study in Taltech University. All the best.')
print(f'Remaining lines {500 - (13 + 17 + 20 + 14)}')